version: 2

build:
  os: ubuntu-22.04
  tools:
    python:
      version: 3.7
      install:
        - requirements: requirements-rtd.txt
        - method: pip
          path: .

sphinx:
  configuration: docs/conf.py
